version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 5
    reviewers:
      - "douglaslinsmeyer"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Enable version updates for npm packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 5
    reviewers:
      - "douglaslinsmeyer"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "build"
      include: "scope"
    ignore:
      # Ignore major version updates for semantic-release
      # to avoid breaking changes in the release process
      - dependency-name: "semantic-release"
        update-types: ["version-update:semver-major"]