name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate-files:
    name: Validate Files
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Validate markdown files
        run: |
          echo "Checking for empty markdown files..."
          find . -name "*.md" -type f -empty -print -exec false {} +
          
      - name: Validate JSON files
        run: |
          echo "Validating manifest.json..."
          jq empty manifest.json
          
      - name: Check file permissions
        run: |
          echo "Checking install.sh is executable..."
          test -x install.sh
          
      - name: Install BATS
        run: |
          sudo apt-get update
          sudo apt-get install -y bats
          
      - name: Run BATS validation tests
        run: |
          chmod +x tests/*.sh tests/*.bats
          bats tests/validation.bats

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          check_together: 'yes'
          scandir: '.'
          format: 'gcc'

  bats-tests:
    name: BATS Tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install BATS
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo apt-get update
            sudo apt-get install -y bats
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew install bats-core
          fi
        
      - name: Run all BATS tests
        run: |
          chmod +x tests/*.sh tests/*.bats
          bash tests/run_bats_tests.sh

  test-installation:
    name: Test Installation
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        install-type: [global, local]
        
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test installation
        run: |
          # Set up test environment
          if [[ "${{ matrix.install-type }}" == "global" ]]; then
            export HOME="$GITHUB_WORKSPACE/test-home"
            mkdir -p "$HOME"
            INSTALL_FLAG=""
          else
            INSTALL_FLAG="--local"
          fi
          
          # Run installation
          bash install.sh $INSTALL_FLAG --force
          
          # Verify installation
          if [[ "${{ matrix.install-type }}" == "global" ]]; then
            CLAUDE_DIR="$HOME/.claude"
          else
            CLAUDE_DIR=".claude"
          fi
          
          # Check key files exist
          test -d "$CLAUDE_DIR"
          test -f "$CLAUDE_DIR/CLAUDE.md"
          test -f "$CLAUDE_DIR/.claude-install-manifest"
          test -d "$CLAUDE_DIR/workflows"
          test -d "$CLAUDE_DIR/personas"
          test -d "$CLAUDE_DIR/templates"
          
          echo "Installation test passed!"

  test-update:
    name: Test Update Scenario
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test update scenario
        run: |
          export HOME="$GITHUB_WORKSPACE/test-home"
          mkdir -p "$HOME"
          
          # First installation
          bash install.sh --force
          
          # Verify first installation
          test -f "$HOME/.claude/CLAUDE.md"
          
          # Modify a file
          echo "Modified" > "$HOME/.claude/CLAUDE.md"
          
          # Run update
          bash install.sh --force
          
          # Verify file was restored
          ! grep -q "Modified" "$HOME/.claude/CLAUDE.md"
          
          echo "Update test passed!"

  test-dry-run:
    name: Test Dry Run
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Test dry run
        run: |
          export HOME="$GITHUB_WORKSPACE/test-home"
          mkdir -p "$HOME"
          
          # Run dry run
          output=$(bash install.sh --dry-run 2>&1)
          
          # Verify no files were created
          test ! -d "$HOME/.claude"
          
          # Verify dry run output
          echo "$output" | grep -q "DRY RUN"
          echo "$output" | grep -q "Would"
          
          echo "Dry run test passed!"

  all-tests:
    name: All Tests
    needs: [validate-files, shellcheck, bats-tests, test-installation, test-update, test-dry-run]
    runs-on: ubuntu-latest
    
    steps:
      - name: All tests passed
        run: echo "All tests passed successfully! ✅"

  create-release:
    name: Create Release if Version Changed
    needs: all-tests
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Note: Using GITHUB_TOKEN here means the tag push won't trigger the release workflow
          # This is a GitHub security feature to prevent infinite workflow loops
          # To enable automatic releases, you would need to use a Personal Access Token (PAT)
          # For now, releases need to be created manually after tags are pushed
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check and create tag
        run: |
          # Get current version from VERSION file
          current_version=$(cat VERSION)
          echo "Current version: $current_version"
          
          # Check if tag already exists
          if git rev-parse "v$current_version" >/dev/null 2>&1; then
            echo "Tag v$current_version already exists, skipping tag creation"
          else
            echo "Creating tag v$current_version"
            
            # Configure git
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            
            # Create annotated tag
            git tag -a "v$current_version" -m "Release version $current_version"
            
            # Push tag
            git push origin "v$current_version"
            
            echo "Tag v$current_version created and pushed"
          fi
          
      - name: Create GitHub Release
        if: success()
        run: |
          current_version=$(cat VERSION)
          
          # Only create release if tag was just created
          if git rev-parse "v$current_version" >/dev/null 2>&1 && ! gh release view "v$current_version" >/dev/null 2>&1; then
            echo "Creating GitHub release for v$current_version"
            
            # Extract changelog section for this version
            changelog=$(awk -v ver="## [$current_version]" '
              $0 ~ ver { found=1; next }
              found && /^## \[/ { exit }
              found { print }
            ' CHANGELOG.md)
            
            # Create release body
            {
              echo "## Installation"
              echo ""
              echo '```bash'
              echo "curl -sSL https://raw.githubusercontent.com/douglaslinsmeyer/claude-environment/v$current_version/install.sh | bash"
              echo '```'
              echo ""
              echo "## What's Changed"
              echo ""
              echo "$changelog"
              echo ""
              echo "---"
              echo ""
              echo "**Full Changelog**: https://github.com/douglaslinsmeyer/claude-environment/blob/main/CHANGELOG.md"
            } > release-body.md
            
            # Create the release
            gh release create "v$current_version" \
              --title "Release $current_version" \
              --notes-file release-body.md \
              --verify-tag
            
            echo "Release created successfully!"
          else
            echo "Release already exists or tag not found, skipping release creation"
          fi